"use client";

import { useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { Icon } from "@/components/icons";
import { useApp } from "@/components/app-provider";
import { prospects } from "@/lib/data";

export default function ProspectsPage() {
  const { saved, saveProspect } = useApp();
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All types");
  const categories = ["All types", ...Array.from(new Set(prospects.map((item) => item.category)))];
  const matches = useMemo(() => prospects.filter((item) => (category === "All types" || item.category === category) && `${item.name} ${item.category} ${item.address}`.toLowerCase().includes(query.toLowerCase())), [category, query]);
  const isSaved = (id: string) => saved.some((item) => item.id === id);
  return <AppShell title="Find prospects" subtitle="Fictional local businesses ranked against your ideal customer profile.">
    <section className="panel overflow-hidden"><div className="border-b border-[#e6ece8] p-4 sm:p-5"><div className="grid gap-3 sm:grid-cols-[1fr_190px]"><label className="relative"><Icon name="search" className="absolute left-3.5 top-3.5 h-4 w-4 text-[#718078]" /><span className="sr-only">Search prospects</span><input className="field pl-10" placeholder="Search businesses or categories" value={query} onChange={(e) => setQuery(e.target.value)} /></label><select className="field" value={category} onChange={(e) => setCategory(e.target.value)} aria-label="Filter by business type">{categories.map((item) => <option key={item}>{item}</option>)}</select></div><p className="mt-3 text-xs text-[#718078]"><span className="font-bold text-[#315044]">Demo data only.</span> These businesses and contacts are fictional.</p></div>
      <div className="grid lg:grid-cols-[1fr_320px]"><div className="divide-y divide-[#edf1ee]">{matches.map((prospect) => <article className="p-4 sm:p-5" key={prospect.id}><div className="flex flex-col justify-between gap-4 sm:flex-row"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-black tracking-tight">{prospect.name}</h2><span className="rounded-full bg-[#e6f7f3] px-2.5 py-1 text-xs font-black text-[#0b6d64]">{prospect.score}% match</span></div><p className="mt-1 text-sm font-semibold text-[#557166]">{prospect.category}</p><p className="mt-3 flex items-center gap-1.5 text-sm text-[#718078]"><Icon name="pin" className="h-4 w-4 text-[#0f766e]" />{prospect.address} <span className="text-[#b1bcb5]">•</span> {prospect.distance}</p><p className="mt-3 max-w-xl text-sm leading-6 text-[#66776e]">{prospect.reason}</p><div className="mt-3 flex flex-wrap gap-2">{prospect.tags.map((tag) => <span key={tag} className="rounded-lg bg-[#f1f5f2] px-2.5 py-1 text-xs font-semibold text-[#557166]">{tag}</span>)}</div></div><div className="shrink-0 sm:text-right"><p className="text-xs font-bold uppercase tracking-wider text-[#829087]">Contact</p><p className="mt-1 max-w-40 text-sm font-semibold text-[#31443b]">{prospect.contact}</p><button onClick={() => saveProspect(prospect)} disabled={isSaved(prospect.id)} className={`mt-4 w-full sm:w-auto ${isSaved(prospect.id) ? "btn-secondary cursor-default border-[#b9ddd3] bg-[#eefbf7] text-[#0b6d64]" : "btn-primary"}`}>{isSaved(prospect.id) ? <><Icon name="check" className="h-4 w-4" />Saved</> : <><Icon name="plus" className="h-4 w-4" />Save to CRM</>}</button></div></div></article>)}{!matches.length && <div className="p-10 text-center"><Icon name="search" className="mx-auto h-7 w-7 text-[#9aa9a0]" /><p className="mt-3 font-bold">No fictional businesses match that search.</p><button onClick={() => { setQuery(""); setCategory("All types"); }} className="mt-2 text-sm font-bold text-[#0f766e]">Clear filters</button></div>}</div>
        <aside className="hidden border-l border-[#e6ece8] bg-[#f8faf8] p-5 lg:block"><p className="eyebrow">Nearby this afternoon</p><div className="relative mt-4 h-80 overflow-hidden rounded-2xl bg-[#dce9df]"><div className="absolute inset-0 opacity-45" style={{ backgroundImage: "linear-gradient(25deg, transparent 47%, #b4ccba 48%, #b4ccba 50%, transparent 51%), linear-gradient(110deg, transparent 46%, #c0d8c6 47%, #c0d8c6 49%, transparent 50%)", backgroundSize: "75px 90px" }} /><div className="absolute left-[20%] top-[17%] h-20 w-28 rotate-12 rounded-3xl border-[14px] border-[#c5dabb]" /><div className="absolute bottom-[16%] right-[16%] h-16 w-20 -rotate-6 rounded-[50%] border-[12px] border-[#c5dabb]" />{prospects.slice(0, 5).map((item, index) => <div key={item.id} className="absolute" style={{ left: `${18 + ((index * 23) % 65)}%`, top: `${20 + ((index * 29) % 62)}%` }}><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-white bg-[#0f766e] text-xs font-black text-white shadow-md">{index + 1}</span></div>)}<div className="absolute bottom-3 left-3 rounded-xl bg-white px-3 py-2 text-xs font-bold shadow-sm">Dublin city centre</div></div><div className="mt-5 rounded-xl bg-white p-4"><p className="text-sm font-black">Tip for this route</p><p className="mt-1 text-sm leading-5 text-[#718078]">Start around Camden Street; the top three matches are less than a kilometre apart.</p></div></aside>
      </div>
    </section>
  </AppShell>;
}
